#include "dvda_helper.h"
#include <cstdio>

// Legitimate implementation of the helper library.
// An attacker replaces this with a malicious version.

extern "C" {

const char* dvda_helper_version()
{
    return "DVDA Helper Library v2.0 (Legitimate)";
}

int dvda_helper_init()
{
    printf("[DVDA-HELPER] Helper library initialized (legitimate version)\n");
    return 0;
}

const char* dvda_helper_generate_report()
{
    return "Report generated by legitimate DVDA helper library";
}

}
